### ISSUE TITLE
Question: comparison with `:History`

### ISSUE THREAD

**Issue by redstreet** [pbogut/fzf-mru.vim#27]
Hi,
Thank you for this plugin which I've been using for a long time!

In your `README.md`, you mention `fzf.vim`'s `: History` doesn't work for you. I'm curious, would you mind sharing how CtrlP is different from `: History`, and specifically the use cases you found missing?

Thanks much!

**Comment by pbogut** [comment]
What I did say in README was that `:History` command from `fzf.vim` did not work for me, but I don't remember why, it was 7 years ago. It probably was lacking some of the `CtrlP` features, so I decided to copy `CtrlP` "engine" for MRU and make it work with `FZF`. I don't even use `FZF` anymore (though I am still using this plugin with ``Telescope` integration).

**Comment by redstreet** [comment]
My bad, I did mean : History. Okay, thanks for the reply. I'll test drive them both and report back if at all I find a difference.

**Comment by mikeboiko** [comment]
I found this plugin because `:History` was not nearly as nice as the old CtrlP MRU feature.
This is what was lacking from `:History` for me:
- It doesn't take frequency into account. If I open a file many times, I want MRU to suggest that file first.
- It doesn't save the recently used files until you exit the session. On neovim, if I wanted to work with 2 separate vim sessions in tmux, I had to do some `rshada` and `wshada` magic to synchronize the recently used files. This is done automatically by this plugin.
