### ISSUE TITLE
Removed file still shows in MRU

### ISSUE THREAD

**Issue by pwntester** [pbogut/fzf-mru.vim#5]
Is there a way to remove items from MRU list when file is deleted from file system?

Thanks!

**Comment by pbogut** [comment]
There is currently no option to ignore deleted files. There is an API to manually manipulate the list. As a workaround you could use something like this:

```
function! Refresh_MRU()
  for l:file in fzf_mru#mrufiles#list('raw')
    let l:to_remove = []
    if !filereadable(l:file)
      call add(l:to_remove, l:file)
    endif
    call fzf_mru#mrufiles#remove(l:to_remove)
  endfor
endfunction


call Refresh_MRU()
```

Calling `Refresh_MRU()` will remove deleted files from the mru list.

I will keep that issue open and will think about adding an option to automatically check for removed files.

**Comment by pwntester** [comment]
Thanks for your quick response, I worked great!

**Comment by lervag** [comment]
Is there a reason why you don't want to make either a simple refresh command or an option to let the MRU command automatically refresh when started? With refresh, I mean to remove files from cache that do not exist.

Another alternative would be to add some sort of hook for users to make such a filter on their own.

**Comment by lervag** [comment]
Or, is this already added with `FZFFreshMru`?

**Comment by pbogut** [comment]
Truth is I'm not doing it because I don't need it. If you fancy creating PR I'm happy to accept it.

**Comment by lervag** [comment]
Ok, I might. But in lack of other documentation, I'm curious: What does `FZFFreshMru` do?

**Comment by pbogut** [comment]
Not my code, I took it from CtrlP, but by the looks of it it's refreshing mru list, filter out removed files but only from the cache file, removed files stays in memory till you restart `vim`. Not sure if it is bug or it suppose to be like that, probably bug. 

If you add this line `cal filter(s:mrufs, '!empty(fzf_mru#utils#glob(v:val, 1)) && !s:excl(v:val)')` (note `s:`) [here](https://github.com/pbogut/fzf-mru.vim/blob/master/autoload/fzf_mru/mrufiles.vim#L91) it will work but not sure about side effects, would have to spend more time on it. I will keep it changed and if I don't see any issues I will probably commit it.

Then you can use `FZFFreshMru` instead of `FZFMru`, probably bit slower, but will make sure removed files are not showing up.

**Comment by lervag** [comment]
Thanks. It seems from my initial testing that this does what I want (except for the bug you mentioned). I'll also make your proposed change, and I'll let you know if I see some unwanted side effects.
